name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  

    - name: Restore dependencies
      run: dotnet restore ./ToDoList/ToDoList.sln

    - name: Build project
      run: dotnet build ./ToDoList/ToDoList.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ./ToDoList.Tests/ToDoList.Tests.csproj --no-build --verbosity normal
