name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Проверка исходного кода
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка .NET SDK версии 8
    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Восстановление зависимостей
    - name: Restore dependencies
      run: dotnet restore ./ToDoList/ToDoList.sln

    # Сборка проекта
    - name: Build project
      run: dotnet build ./ToDoList/ToDoList.sln --no-restore --configuration Debug

    # Проверка содержимого тестовой папки
    - name: Verify test build output
      run: ls -R ./ToDoList.Tests/bin/Debug/net8.0

    # Сборка Docker-образа
    - name: Build Docker Image
      run: docker build -f ./ToDoList/Dockerfile -t my-todolist:latest ./ToDoList

    # Запуск контейнера
    - name: Run Container
      run: docker run -d -p 8080:8080 --name todolist my-todolist:latest

    # Запуск тестов в контейнере
    - name: Run Tests
      run: |
        docker exec todolist dotnet test ./ToDoList.Tests/ToDoList.Tests.csproj --no-build --logger "console;verbosity=detailed"

    # Проверка работы контейнера
    - name: Test Container Health
      run: curl --fail http://localhost:8080 || exit 1

    # Остановка и удаление контейнера
    - name: Cleanup
      run: |
        docker stop todolist
        docker rm todolist
