name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Проверка исходного кода
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка .NET SDK версии 8
    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Сборка Docker-образа
    - name: Build Docker image
      run: docker build -t todolist-app ./ToDoList

    # (Опционально) Публикация Docker-образа в Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push stardewjan/todolist:tagname
