name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Проверка исходного кода
    - name: Checkout code
      uses: actions/checkout@v3

    # Сборка Docker-образа
    - name: Build Docker Image
      run: docker build -f ./ToDoList/Dockerfile -t my-todolist:latest ./ToDoList

    # Запуск контейнера
    - name: Run Container
      run: docker run -d --name todolist my-todolist:latest

    # Запуск тестов в контейнере
    - name: Run Tests
      run: |
        docker exec todolist dotnet test /src/ToDoList.Tests/ToDoList.Tests.csproj --no-build --logger "console;verbosity=detailed"

    # Проверка работы контейнера
    - name: Test Container Health
      run: curl --fail http://localhost:8080 || exit 1

    # Остановка и удаление контейнера
    - name: Cleanup
      run: |
        docker stop todolist
        docker rm todolist
