name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Проверка исходного кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t todo-list-app:latest ./ToDoList

      # Запуск тестов внутри контейнера
      - name: Run tests
        run: docker run --rm todo-list-app:latest
