name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # Checkout исходного кода
    - name: Checkout code
      uses: actions/checkout@v3

    # Сборка Docker-образа
    - name: Build Docker image
      run: docker build -f ToDoList/Dockerfile .

    # Запуск unit-тестов внутри Docker-контейнера
    - name: Run tests in Docker container
      run: |
        docker run --rm $(docker build -q -f ToDoList/Dockerfile .) \
        dotnet test /src/ToDoList.Tests/ToDoList.Tests.csproj \
        --logger "console;verbosity=detailed"

